### ISSUE TITLE
Add NPM/Yarn/Bower support for installation and version management.

### ISSUE THREAD

**Issue by gvsrepins** [takenet/blip-chat-widget#3]
It would be very helpful if the BLIP script was plugable  with the version management tools largely used in the world at this moment.

Regards,

**Comment by ravpacheco** [comment]
Hi @gvsrepins,

thanks for your comment. 👍 
Actually this package is already in NPM/Yarn

please check this link [https://www.npmjs.com/package/blip-chat-widget](https://www.npmjs.com/package/blip-chat-widget)

**Comment by ravpacheco** [comment]
I'm closing your issue.

Please let me know if you have more questions
