### ISSUE TITLE
How to change the default placeholder on sending new messages?

### ISSUE THREAD

**Issue by levindoneto** [takenet/blip-chat-widget#38]
I can't find a way to change this placeholder on sending new messages.
My bot is all in English, but this placeholder isn't changeable apparently 😞 

![image](https://user-images.githubusercontent.com/12832687/116006549-206ae380-a5e2-11eb-8432-c293a9c0bbf3.png)

**Comment by Estavaringo** [comment]
Hello

Have you tried change your chatbot culture at Blip Portal?

Check how to do this:
https://forum.blip.ai/t/solved-customize-message-input-placeholder-to-english/1416

**Comment by levindoneto** [comment]
Got it now, thanks @Estavaringo 🙂
