### ISSUE TITLE
Please clarify recommended setup for React Apps

### ISSUE THREAD

**Issue by rturk** [takenet/blip-chat-widget#4]
Please clarify the best way to configure this client when using React Framework

**Comment by samwx** [comment]
Hello @rturk!

Thanks for your feedback and for using blip chat widget. To use with react app, you can install blip-chat-widget from npm (`npm i -S blip-chat-widget`) and import them via destructuring assignment.

We made an example to clarify your question:

```javascript
import React from "react";
import ReactDOM from "react-dom";
import { BlipChat } from "blip-chat-widget";

import "./styles.css";

class App extends React.Component {
  componentDidMount() {
    new BlipChat()
      .withAppKey("YOUR-APP-KEY")
      .withButton({ color: "#2CC3D5" })
      .build();
  }
  render() {
    return (
      <div className="App">
        <h1>Hello world</h1>
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

Thanks!

**Comment by rturk** [comment]
@samwx amazing, that was fast. Are you a bot?

**Comment by samwx** [comment]
@rturk hahahaha, thanks! But no, I'm a real person 😄

**Comment by guiqis** [comment]
Hi @rturk , is this code still working or some updates may be required?
I'm getting an error 'TypeError: undefined is not an object (evaluating 'self.navigator.userAgent.toLowerCase')'

**Comment by RobertDS07** [comment]
Same here, I guess.
![image](https://user-images.githubusercontent.com/63268954/166812685-4ca5f469-0f38-4635-90f8-25890127bbb7.png)
Ps: I'm using Nextjs, maybe anything with SSR?

**Comment by RobertDS07** [comment]
Solved importing blip-chat with dynamically import
![image](https://user-images.githubusercontent.com/63268954/166815560-42df82fd-c643-4d96-b297-ef23bc581dab.png)
